export const supportedLang = [
  { id: 1, lang: 'Afrikaans' },
  { id: 2, lang: 'Amharic - አማርኛ' },
  { id: 3, lang: 'Azerbaijani - Azərbaycanca' },
  { id: 4, lang: 'Bangla - বাংলা' },
  { id: 5, lang: 'Bahasa Indonesia' },
  { id: 6, lang: 'Bahasa Melayu' },
  { id: 7, lang: 'Catalan - Català' },
  { id: 8, lang: 'Czech - Čeština' },
  { id: 9, lang: 'Danish - Dansk' },
  { id: 10, lang: 'German - Deutsch' },
  { id: 11, lang: 'English' },
  { id: 12, lang: 'Spanish - Español' },
  { id: 13, lang: 'Euskara' },
  { id: 14, lang: 'Filipino' },
  { id: 15, lang: 'Français' },
  { id: 16, lang: 'Basa Jawa' },
  { id: 17, lang: 'Galego' },
  { id: 18, lang: 'Gujarati - ગુજરાતી' },
  { id: 19, lang: 'Croatian - Hrvatski' },
  { id: 20, lang: 'Zulu - IsiZulu' },
  { id: 21, lang: 'Icelandic - Íslenska' },
  { id: 22, lang: 'Italian - Italiano' },
  { id: 23, lang: 'Kannada - ಕನ್ನಡ' },
  { id: 24, lang: 'Knmer - ភាសាខ្មែរ' },
  { id: 25, lang: 'Latviešu' },
  { id: 26, lang: 'Lithuanian - Lietuvių' },
  { id: 27, lang: 'Malayalam - മലയാളം' },
  { id: 28, lang: 'Marathi - मराठी' },
  { id: 29, lang: 'Hungarian - Magyar' },
  { id: 30, lang: 'Lao - ລາວ' },
  { id: 31, lang: 'Nederlands' },
  { id: 32, lang: 'Nepali language - नेपाली भाषा' },
  { id: 33, lang: 'Norsk bokmål' },
  { id: 34, lang: 'Polish - Polski' },
  { id: 35, lang: 'Portuguese - Português' },
  { id: 36, lang: 'Romanian - Română' },
  { id: 37, lang: 'Sinhala - සිංහල' },
  { id: 38, lang: 'Slovenian - Slovenščina' },
  { id: 39, lang: 'Sundanese language - Basa Sunda' },
  { id: 40, lang: 'Slovak - Slovenčina' },
  { id: 41, lang: 'Finnish - Suomi' },
  { id: 42, lang: 'Swedish - Svenska' },
  { id: 43, lang: 'Kiswahili' },
  { id: 44, lang: 'Georgian - ქართული' },
  { id: 45, lang: 'Armenian - Հայերեն' },
  { id: 46, lang: 'Tamil - தமிழ்' },
  { id: 47, lang: 'Telugu - తెలుగు' },
  { id: 48, lang: 'Vietnamese - Tiếng Việt' },
  { id: 49, lang: 'Turkish - Türkçe' },
  { id: 50, lang: 'urdu - اُردُو' },
  { id: 51, lang: 'Greek - Ελληνικά' },
  { id: 52, lang: 'Bulgarian - български' },
  { id: 53, lang: 'Russian - Pусский' },
  { id: 54, lang: 'Serbian - Српски' },
  { id: 55, lang: 'Ukrainian - Українська' },
  { id: 56, lang: 'Korean - 한국어' },
  { id: 57, lang: 'Chinese - 中文' },
  { id: 58, lang: 'Japanese - 日本語' },
  { id: 59, lang: 'Hindi - हिन्दी' },
  { id: 60, lang: 'Thai - ภาษาไทย' }
]

export const supportedRegion = [
  { id: 1, langId: 1, code: 'af-ZA', display: 'South Africa(af-ZA)' },
  { id: 2, langId: 2, code: 'am-ET', display: 'Ethiopia(am-ET)' },
  { id: 3, langId: 3, code: 'az-AZ', display: 'Azerbaijan(az-AZ)' },
  { id: 4, langId: 4, code: 'bn-BD', display: 'Bangladesh(bn-BD)' },
  { id: 5, langId: 4, code: 'bn-IN', display: 'India(bn-IN)' },
  { id: 6, langId: 5, code: 'id-ID', display: 'Indonesia(id-ID)' },
  { id: 7, langId: 6, code: 'ms-MY', display: 'Malaysia(ms-MY)' },
  { id: 8, langId: 7, code: 'ca-ES', display: 'Spain(ca-ES)' },
  { id: 9, langId: 8, code: 'cs-CZ', display: 'Czechia(cs-CZ)' },
  { id: 10, langId: 9, code: 'da-DK', display: 'Denmark(da-DK)' },
  { id: 11, langId: 10, code: 'de-DE', display: 'Germany(de-DE)' },
  { id: 12, langId: 11, code: 'en-AU', display: 'Australia(en-AU)' },
  { id: 13, langId: 11, code: 'en-CA', display: 'Canada(en-CA)' },
  { id: 14, langId: 11, code: 'en-IN', display: 'India(en-IN)' },
  { id: 15, langId: 11, code: 'en-KE', display: 'Kenya(en-KE)' },
  { id: 16, langId: 11, code: 'en-TZ', display: 'Kenya(en-TZ)' },
  { id: 17, langId: 11, code: 'en-GH', display: 'Ghana(en-GH)' },
  { id: 18, langId: 11, code: 'en-NZ', display: 'New Zealand(en-NZ)' },
  { id: 19, langId: 11, code: 'en-NG', display: 'Nigeria(en-NG)' },
  { id: 20, langId: 11, code: 'en-ZA', display: 'South Africa(en-ZA)' },
  { id: 21, langId: 11, code: 'en-PH', display: 'Philippines(en-PH)' },
  { id: 22, langId: 11, code: 'en-GB', display: 'United Kingdom(en-GB)' },
  { id: 23, langId: 11, code: 'en-US', display: 'United States(en-US)' },
  { id: 24, langId: 12, code: 'es-AR', display: 'Argentina(es-AR)' },
  { id: 25, langId: 12, code: 'es-BO', display: 'Bolivia(es-BO)' },
  { id: 26, langId: 12, code: 'es-CL', display: 'Chile(es-CL)' },
  { id: 27, langId: 12, code: 'es-CO', display: 'Colombia(es-CO)' },
  { id: 28, langId: 12, code: 'es-CR', display: 'Costa Rica(es-CR)' },
  { id: 29, langId: 12, code: 'es-EC', display: 'Ecuador(es-EC)' },
  { id: 30, langId: 12, code: 'es-SV', display: 'El Salvador(es-SV)' },
  { id: 31, langId: 12, code: 'es-ES', display: 'España(es-ES)' },
  { id: 32, langId: 12, code: 'es-US', display: 'Estados Unidos(es-US)' },
  { id: 33, langId: 12, code: 'es-GT', display: 'Guatemala(es-GT)' },
  { id: 34, langId: 12, code: 'es-HN', display: 'Honduras(es-HN)' },
  { id: 35, langId: 12, code: 'es-MX', display: 'México(es-MX)' },
  { id: 36, langId: 12, code: 'es-NI', display: 'México(es-NI)' },
  { id: 37, langId: 12, code: 'es-PA', display: 'Panamá(es-PA)' },
  { id: 38, langId: 12, code: 'es-PY', display: 'Paraguay(es-PY)' },
  { id: 39, langId: 12, code: 'es-PE', display: 'Perú(es-PE)' },
  { id: 40, langId: 12, code: 'es-PR', display: 'Puerto Rico(es-PR)' },
  { id: 41, langId: 12, code: 'es-DO', display: 'República Dominicana(es-DO)' },
  { id: 42, langId: 12, code: 'es-UY', display: 'Uruguay(es-UY)' },
  { id: 43, langId: 12, code: 'es-VE', display: 'Venezuela(es-VE)' },
  { id: 44, langId: 13, code: 'eu-ES', display: 'Spain(eu-ES)' },
  { id: 45, langId: 14, code: 'fil-PH', display: 'Philippines(fil-PH)' },
  { id: 46, langId: 15, code: 'fr-FR', display: 'France(fr-FR)' },
  { id: 47, langId: 16, code: 'jv-ID', display: 'Indonesia(jv-ID)' },
  { id: 48, langId: 17, code: 'gl-ES', display: 'Spain(gl-ES)' },
  { id: 49, langId: 18, code: 'gu-IN', display: 'India(gu-IN)' },
  { id: 50, langId: 19, code: 'hr-HR', display: 'Croatia(hr-HR)' },
  { id: 51, langId: 20, code: 'zu-ZA', display: 'South Africa(zu-ZA)' },
  { id: 52, langId: 21, code: 'is-IS', display: 'Iceland(is-IS)' },
  { id: 53, langId: 22, code: 'it-IT', display: 'Italia(it-IT)' },
  { id: 54, langId: 22, code: 'it-CH', display: 'Svizzera(it-CH)' },
  { id: 55, langId: 23, code: 'kn-IN', display: 'India(kn-IN)' },
  { id: 56, langId: 24, code: 'km-KH', display: 'Cambodia(km-KH)' },
  { id: 57, langId: 25, code: 'lv-LV', display: 'Latvia(lv-LV)' },
  { id: 58, langId: 26, code: 'lt-LT', display: 'Lithuania(lt-LT)' },
  { id: 59, langId: 27, code: 'ml-IN', display: 'India(ml-IN)' },
  { id: 60, langId: 28, code: 'mr-IN', display: 'India(mr-IN)' },
  { id: 61, langId: 29, code: 'hu-HU', display: 'Hungary(hu-HU)' },
  { id: 62, langId: 30, code: 'lo-LA', display: 'Laos(lo-LA)' },
  { id: 63, langId: 31, code: 'nl-NL', display: 'Netherlands(nl-NL)' },
  { id: 64, langId: 32, code: 'ne-NP', display: 'Nepal(ne-NP)' },
  { id: 65, langId: 33, code: 'nb-NO', display: 'Norway(nb-NO)' },
  { id: 66, langId: 34, code: 'pl-PL', display: 'Poland(pl-PL)' },
  { id: 67, langId: 35, code: 'pt-BR', display: 'Brasil(pt-BR)' },
  { id: 68, langId: 35, code: 'pt-PT', display: 'Portugal(pt-PT)' },
  { id: 69, langId: 36, code: 'ro-RO', display: 'Romania(ro-RO)' },
  { id: 70, langId: 37, code: 'si-LK', display: 'Sri Lanka(si-LK)' },
  { id: 71, langId: 38, code: 'sl-SI', display: 'Slovenia(sl-SI)' },
  { id: 72, langId: 39, code: 'su-ID', display: 'Indonesia(su-ID)' },
  { id: 73, langId: 40, code: 'sk-SK', display: 'Slovakia(sk-SK)' },
  { id: 74, langId: 41, code: 'fi-FI', display: 'Finland(fi-FI)' },
  { id: 75, langId: 42, code: 'sv-SE', display: 'Sweden(sv-SE)' },
  { id: 76, langId: 43, code: 'sw-TZ', display: 'Tanzania(sw-TZ)' },
  { id: 77, langId: 43, code: 'sw-KE', display: 'Kenya(sw-KE)' },
  { id: 78, langId: 44, code: 'ka-GE', display: 'Georgia(ka-GE)' },
  { id: 79, langId: 45, code: 'hy-AM', display: 'Armenia(hy-AM)' },
  { id: 80, langId: 46, code: 'ta-IN', display: 'India(ta-IN)' },
  { id: 81, langId: 46, code: 'ta-SG', display: 'Singapore(ta-SG)' },
  { id: 82, langId: 46, code: 'ta-LK', display: 'SriLanka(ta-LK)' },
  { id: 83, langId: 46, code: 'ta-MY', display: 'Malaysia(ta-MY)' },
  { id: 84, langId: 47, code: 'te-IN', display: 'India(te-IN)' },
  { id: 85, langId: 48, code: 'vi-VN', display: 'Vietnam(vi-VN)' },
  { id: 85, langId: 49, code: 'tr-TR', display: 'Türkiye(tr-TR)' },
  { id: 86, langId: 50, code: 'ur-PK', display: 'Pakistan(ur-PK)' },
  { id: 87, langId: 50, code: 'ur-IN', display: 'India(ur-IN)' },
  { id: 88, langId: 51, code: 'el-GR', display: 'Greece(el-GR)' },
  { id: 89, langId: 52, code: 'bg-BG', display: 'Bulgaria(bg-BG)' },
  { id: 90, langId: 53, code: 'ru-RU', display: 'Russia(ru-RU)' },
  { id: 91, langId: 54, code: 'sr-RS', display: 'Serbia(sr-RS)' },
  { id: 92, langId: 55, code: 'uk-UA', display: 'Ukraine(uk-UA)' },
  { id: 93, langId: 56, code: 'ko-KR', display: 'South Korea(ko-KR)' },
  { id: 94, langId: 57, code: 'cmn-Hans-CN', display: 'Chinese(cmn-Hans-CN)' },
  { id: 95, langId: 57, code: 'cmn-Hans-HK', display: 'Hong Kong(cmn-Hans-HK)' },
  { id: 96, langId: 57, code: 'cmn-Hant-TW', display: 'Taiwan(cmn-Hant-TW)' },
  { id: 97, langId: 57, code: 'yue-Hant-HK', display: 'Hong Kong(yue-Hant-HK)' },
  { id: 98, langId: 58, code: 'ja-JP', display: 'Japan(ja-JP)' },
  { id: 99, langId: 59, code: 'hi-IN', display: 'India(hi-IN)' },
  { id: 100, langId: 60, code: 'th-TH', display: 'Thailand(th-TH)' }
]
